name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Upload Mod
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build publish --stacktrace --rerun-tasks
        env:
          BRANCH_NAME: ${{ github.ref }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
